version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: forensix-server
    healthcheck:
      test: ["CMD", "test", "-f", "/app/utils/predictor/finalized_model.sav"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - type: bind
        source: ./data
        target: /app/data
        read_only: true
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: forensix-client
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    container_name: "forensix-mongodb"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
