version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: forensix-server-image
    container_name: forensix-server
    volumes:
      - type: bind
        source: ./data2
        target: /app/data
        read_only: true
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: forensix-client-image
    container_name: forensix-client
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    container_name: "forensix-mongodb"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: forensix-mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000
