version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chmarax/forensix:server
    container_name: forensix-server
    volumes:
      - type: bind
        source: ./dataExample
        target: /app/data
        read_only: true
    ports:
      - "3001:3001"
    links:
      - mongodb
    depends_on:
      - mongodb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chmarax/forensix:client
    container_name: forensix-client
    environment:
      - API_HOST=localhost
    ports:
      - "3000:3000"
    links:
      - server
    depends_on:
      - server
  mongodb:
    image: mongo:latest
    container_name: "forensix-mongodb"
    volumes:
      - ./mongo-volume:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
