'use strict';
// Generates results/leaderboard.md FROM results.json. Never hand-written.
// The audit found the previous leaderboard disagreed with its own data (it
// rendered cross-architecture determinism as a tick for a candidate that had no
// cross-architecture run). Unmeasured now renders as "not measured".

const fs = require('node:fs');
const path = require('node:path');

const RESULTS_DIR = process.env.RESULTS_DIR || path.join(__dirname, '..', 'results');

function fmt(v, digits = 3) {
  if (v === null || v === undefined || Number.isNaN(v)) return 'not measured';
  return Number(v).toFixed(digits);
}
function pct(v, digits = 1) {
  if (v === null || v === undefined || Number.isNaN(v)) return 'not measured';
  return `${(v * 100).toFixed(digits)}%`;
}

function main() {
  const results = JSON.parse(fs.readFileSync(path.join(RESULTS_DIR, 'results.json'), 'utf8'));
  const crossPath = path.join(RESULTS_DIR, 'cross-arch-comparison.json');
  const cross = fs.existsSync(crossPath) ? JSON.parse(fs.readFileSync(crossPath, 'utf8')) : null;
  const detPath = path.join(RESULTS_DIR, 'determinism-summary.json');
  const det = fs.existsSync(detPath) ? JSON.parse(fs.readFileSync(detPath, 'utf8')) : null;
  const parityPath = path.join(RESULTS_DIR, 'artifact-parity.json');
  const parity = fs.existsSync(parityPath) ? JSON.parse(fs.readFileSync(parityPath, 'utf8')) : null;

  const c = results.census || results.fixture.census;
  const lim = results.fixture.limitations;
  // Sorted by the FROZEN taxonomy policy (macro over all 20 core labels), not by
  // the evaluable policy. The evaluable denominator varies per candidate (it
  // excludes zero-gold labels a candidate never predicts), so sorting on it
  // structurally rewards abstaining and is not a like-for-like ranking.
  const rows = results.candidates.slice().sort(
    (a, b) => (b.macro_f1_fixed_core.value ?? -1) - (a.macro_f1_fixed_core.value ?? -1)
  );
  const poweredOrder = results.candidates.slice()
    .filter((r) => r.macro_f1_powered_only && r.macro_f1_powered_only.value !== null)
    .sort((a, b) => b.macro_f1_powered_only.value - a.macro_f1_powered_only.value);

  const L = [];
  L.push('# Classifier bench leaderboard — ChmaraX/forensix#137');
  L.push('');
  L.push('> **No winner is declared in this artifact.** This is a results table, not a decision.');
  L.push('> The decision belongs to [#126](https://github.com/ChmaraX/forensix/issues/126), reading');
  L.push('> these numbers.');
  L.push('>');
  L.push('> **No ordering here is stable.** The table is sorted by macro-F1 over the fixed 20-label');
  L.push('> taxonomy because that is the frozen policy, but three defensible macro policies give three');
  L.push('> different orderings and the bootstrap intervals overlap heavily. Read the CI column before');
  L.push('> reading the order.');
  L.push('');
  L.push('> **Generated by code.** `harness/make_leaderboard.js` from `results.json`. Do not hand-edit:');
  L.push('> regenerate instead. Every number below resolves to a field in `results.json`.');
  L.push('');
  L.push(`Run \`${results._generator.generated_at}\` · rendered \`${new Date().toISOString()}\` · host \`${results.environment.platform}/${results.environment.arch}\` · Node \`${results.environment.node_version}\` · ORT \`${results.environment.ort_version}\``);
  L.push(`ORT threads: intra=${results.environment.ort_session_options.intraOpNumThreads}, inter=${results.environment.ort_session_options.interOpNumThreads}, graph opt \`${results.environment.ort_session_options.graphOptimizationLevel}\` · network isolated: \`${results.environment.network_isolated}\``);
  if (results._generator.rescored_by) {
    L.push('');
    L.push(`> **Scoring recomputed** by \`${path.basename(results._generator.rescored_by.script)}\` at \`${results._generator.rescored_by.generated_at}\` from the committed per-row predictions. Inference was NOT re-run (\`inference_rerun: ${results._generator.rescored_by.inference_rerun}\`); throughput, footprint, determinism hashes and artifact verification are carried verbatim from the measured run.`);
  }
  L.push('');

  L.push('## Ground truth and its limits');
  L.push('');
  L.push(`- **${c.row_count} rows**, ${c.distinct_urls} distinct URLs, ${c.distinct_etld1} domain groups (registrable domains plus browser-internal groups), **${c.persona_count} personas** (issue asked for 500+ rows).`);
  L.push(`- Persona split: ${Object.entries(c.personas).map(([k, v]) => `\`${k}\` ${v}`).join(', ')}. ${lim.persona_note}`);
  L.push(`- Domain concentration: top domain \`${c.top_domain.etld1}\` is ${pct(c.top_domain.share)} of rows; top 12 domains are ${pct(c.top12_domain_share)}.`);
  L.push(`- ${c.multi_label_rows} rows carry more than one gold label; ${c.ambiguous_rows} are flagged ambiguous by the labeller.`);
  L.push(`- **Labels with no gold rows:** ${lim.zero_gold_labels.map((l) => `\`${l}\``).join(', ') || 'none'}.`);
  L.push(`- **Adult recall is UNMEASURABLE.** ${lim.adult_note}`);
  L.push(`- Non-English rows: ${lim.non_english_rows}. Held-out split: ${lim.held_out_split}`);
  L.push('');

  // Special-category cell. Renders the one-sided bound when zero events were
  // observed, and never renders an unmeasurable direction as a number.
  const scCell = (dir, total) => {
    if (!dir.measurable) return '**unmeasurable** (no gold rows)';
    if (dir.count === 0 && dir.rate_upper_95 !== null && dir.rate_upper_95 !== undefined) {
      return `0/${total} (≤${(dir.rate_upper_95 * 100).toFixed(1)}% by rule of three)`;
    }
    return `${dir.count}/${total}`;
  };

  L.push('## Results');
  L.push('');
  L.push('Sorted by **macro-F1 (fixed 20)**, the taxonomy\'s frozen policy. The other two macro columns are published beside it because they order the field differently — see "How to read the three macro-F1 columns".');
  L.push('');
  L.push('| Candidate | Family | macro-F1 (fixed 20) | macro-F1 (evaluable) | macro-F1 (powered 7) | 95% CI (domain bootstrap, evaluable) | micro-F1 | Coverage | Exact-set | Adult FP | Adult FN | Health FP | Health FN | rows/sec | Footprint | Licence | Same-proc | Separate-proc | Cross-arch |');
  L.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|');
  for (const r of rows) {
    const ci = r.bootstrap_ci && r.bootstrap_ci.applicable
      ? `${fmt(r.bootstrap_ci.ci95_low)}–${fmt(r.bootstrap_ci.ci95_high)}`
      : 'not measured';
    const adult = r.special_category_confusion.adult_sexual_content;
    const health = r.special_category_confusion.health_medical;
    const sep = det && det.per_candidate && det.per_candidate[r.id]
      ? (det.per_candidate[r.id].match ? 'match' : 'MISMATCH')
      : 'not measured';
    const xaEntry = cross && cross.per_candidate ? cross.per_candidate[r.id] : null;
    const xa = xaEntry && xaEntry.measured
      ? (xaEntry.decision_hash_match ? 'decisions match' : `decisions differ (${xaEntry.differing_label_sets} label sets)`)
      : 'not measured';
    const evalCell = `${fmt(r.macro_f1_evaluable.value)} (n=${r.macro_f1_evaluable.label_count})`;
    const powered = r.macro_f1_powered_only && r.macro_f1_powered_only.value !== null
      ? `${fmt(r.macro_f1_powered_only.value)} (n=${r.macro_f1_powered_only.label_count})`
      : 'not measured';
    const lic = r.licence ? r.licence.name : 'not recorded';
    L.push(
      `| \`${r.id}\` | ${r.family} | **${fmt(r.macro_f1_fixed_core.value)}** | ${evalCell} | ${powered} | ${ci} | ${fmt(r.micro_f1)} | ${pct(r.coverage)} | ${fmt(r.multi_label_row_metrics.exact_set_match)} | ${scCell(adult.false_positive, adult.gold_negatives)} | ${scCell(adult.false_negative, adult.gold_positives)} | ${scCell(health.false_positive, health.gold_negatives)} | ${scCell(health.false_negative, health.gold_positives)} | ${r.throughput.rows_per_sec.toFixed(0)} | ${r.disk_footprint.human} | ${lic} | ${r.determinism.same_process_repeat_match ? 'match' : 'MISMATCH'} | ${sep} | ${xa} |`
    );
  }
  L.push('');
  L.push('> **Abstention is spelled `unclassified`, which is itself a scored core label.** A candidate that abstains therefore accrues `unclassified` false positives against the single gold `unclassified` row. `ut1-domain-list-v2-strict`\'s non-zero macro/micro/exact-set numbers are entirely that artefact next to 0.0% coverage, not evidence of any classification ability. Coverage and macro-F1 are not independent axes.');
  L.push('');

  if (results.failures.length) {
    L.push('### Candidates that failed to run');
    L.push('');
    for (const f of results.failures) L.push(`- \`${f.id}\`: ${f.error}`);
    L.push('');
  }

  L.push('## How to read the three macro-F1 columns');
  L.push('');
  L.push('Standard F1 is undefined for a label with no gold rows and no predictions, so no single number serves every purpose honestly. All three policies are published, and they disagree:');
  L.push('');
  L.push(`- **fixed 20** — ${rows[0]?.macro_f1_fixed_core.policy || ''} This is the taxonomy's frozen policy (research/137-taxonomy-proposal.md §3: "averaged over exactly those 20 — never over a subset") and the sort key here. It is dominated by what this fixture cannot test.`);
  L.push(`- **evaluable** — ${rows[0]?.macro_f1_evaluable.policy || ''} It charges for false positives on zero-gold labels, but its DENOMINATOR VARIES PER CANDIDATE (shown as \`n=\` in the cell), because it excludes zero-gold labels a candidate never predicted. A candidate that abstains more is scored over fewer labels, so this policy structurally rewards abstention and is not a like-for-like comparison.`);
  L.push(`- **powered 7** — ${rows[0]?.macro_f1_powered_only.policy || ''} This is the ONLY macro computed over an identical label set for every candidate, so it is the closest thing here to a like-for-like number — but 7 labels is a narrow base and it discards the zero-gold false-positive signal that the evaluable policy captures.`);
  L.push('');
  if (poweredOrder.length) {
    L.push('**The policies reverse the order.** Sorted by the fixed-20 policy the leaders are ' +
      rows.slice(0, 3).map((r) => `\`${r.id}\` (${fmt(r.macro_f1_fixed_core.value)})`).join(', ') +
      '. Sorted by the powered-7 policy they are ' +
      poweredOrder.slice(0, 3).map((r) => `\`${r.id}\` (${fmt(r.macro_f1_powered_only.value)})`).join(', ') +
      '. Neither ordering is more correct than the other, and the bootstrap intervals overlap across most of the field. **No ordering in this bench is statistically supportable; do not read any column as a ranking.**');
    L.push('');
  }
  L.push('Per-label state is explicit in `results.json` `per_class[label].state`: `scored`, `underpowered`, `no-gold-rows-no-predictions`, or `no-gold-rows-false-positives-only`. A label is never silently scored 0 for being untestable.');
  L.push('');
  L.push('The 95% interval is a **percentile** domain-cluster bootstrap, not bias-corrected. The evaluable label set is recomputed per resample, so the resample median can sit slightly below the point estimate; both are in `results.json` `bootstrap_ci`.');
  L.push('');
  L.push('## Special-category labels');
  L.push('');
  L.push('`adult_sexual_content` and `health_medical` are GDPR Article 9 special-category outputs and are reported separately in both directions, per research/137-taxonomy-proposal.md ("SC labels (13, 14) get their own reported confusion rows").');
  L.push('');
  const healthGold = c.per_label.health_medical.gold_rows;
  const healthDomains = c.per_label.health_medical.distinct_etld1;
  const healthRecalls = rows.map((r) => {
    const h = r.special_category_confusion.health_medical;
    return h.false_negative.measurable && h.gold_positives > 0
      ? (h.gold_positives - h.false_negative.count) / h.gold_positives
      : null;
  }).filter((v) => v !== null);
  if (healthRecalls.length) {
    L.push(`- **Health & Medical recall is ${fmt(Math.min(...healthRecalls), 2)}–${fmt(Math.max(...healthRecalls), 2)}** across ${healthRecalls.length} configurations. Both directions are MEASURABLE here (${healthGold} gold rows on ${healthDomains} registrable domains), unlike Adult. **UNDERPOWERED:** ${healthGold} gold rows is far below the declared power floor, so treat the spread as indicative, not as a ranking.`);
  }
  const adultFps = rows.map((r) => r.special_category_confusion.adult_sexual_content.false_positive.count).filter((v) => v !== null && v !== undefined);
  if (adultFps.length) {
    const total = rows[0].special_category_confusion.adult_sexual_content.gold_negatives;
    L.push(`- **Adult false positives range ${Math.min(...adultFps)}–${Math.max(...adultFps)} of ${total}** across all ${adultFps.length} configurations: ` +
      rows.map((r) => `\`${r.id}\` ${r.special_category_confusion.adult_sexual_content.false_positive.count}`).join(', ') + '.');
  }
  L.push(`- **Adult recall is UNMEASURABLE.** ${lim.adult_note}`);
  L.push('');

  L.push('## Per-candidate detail');
  L.push('');
  for (const r of rows) {
    L.push(`### \`${r.id}\``);
    L.push('');
    L.push(`- Family: ${r.family} · engine: \`${r.engine_kind}\` · input: \`${r.input_mode}\``);
    if (r.model) L.push(`- Model \`${r.model.id}\` @ revision \`${r.model.revision}\`, ONNX sha256 \`${r.model.sha256.slice(0, 16)}…\``);
    L.push(`- Supervision: \`${r.supervision_declaration.kind}\` — ${r.supervision_declaration.source}`);
    if (r.supervision_declaration.template) L.push(`  - Hypothesis template: \`${r.supervision_declaration.template}\``);
    if (r.licence) L.push(`- Licence: **${r.licence.name}** (${r.licence.holder}) — authority: ${r.licence.authority || 'see source'}. ${r.licence.note}`);
    // Decision rule, score axis and the unswept emission band, rendered per
    // candidate: these ARE the operating point, and they are not commensurable
    // across candidates.
    const axis = Array.isArray(r.coverage_accuracy_sweep) && r.coverage_accuracy_sweep[0]
      ? r.coverage_accuracy_sweep[0].axis
      : (r.engine_kind === 'lookup-table' ? 'rule-match (categorical)' : 'not recorded');
    L.push(`- Decision rule: \`${JSON.stringify(r.decision)}\` · swept axis: \`${axis}\``);
    if (r.engine_kind !== 'lookup-table' && r.decision && r.decision.multiLabelDelta !== null && r.decision.multiLabelDelta !== undefined) {
      L.push(`  - \`multiLabelDelta\` = ${r.decision.multiLabelDelta} is a **fixed, hand-chosen, UNSWEPT** band in \`${r.supervision_declaration.kind === 'hypothesis-template' ? 'entailment-probability' : 'cosine'}\` units. It sets how many labels each row emits, so macro-F1, micro-F1, exact-set match and the Adult/Health false-positive counts are all functions of it. It is not comparable across candidates with different score axes, and it is held constant at every sweep point.`);
    }
    const violations = Array.isArray(r.supervision.violations) ? r.supervision.violations.length : 'not recorded';
    const removalApplied = r.engine_details ? r.engine_details.overlap_removal_applied : undefined;
    if (r.engine_kind === 'lookup-table') {
      // A 4.78M-entry published table is not declarable entry-by-entry, so the
      // generic "0 declared rule domains / 0 violations" line reads as a
      // contradiction next to a measured overlap count. Render what was actually
      // done instead.
      L.push(`- Contamination guard: not applicable to a ${(r.engine_details?.entries_before_overlap_removal ?? 0).toLocaleString('en-US')}-entry published table; overlap is MEASURED directly rather than declared. Exemplars: ${r.supervision.exemplar_count}. Guard violations: **${violations}**.`);
      if (r.supervision.post_removal_fixture_hits !== undefined) {
        L.push(removalApplied === false
          ? `  - External-table overlap: **${r.supervision.post_removal_fixture_hits} of ${c.row_count} fixture rows** match the published table. No removal was applied in this configuration. ${r.engine_details.removal_note}`
          : `  - External-table overlap after removal: **${r.supervision.post_removal_fixture_hits} of ${c.row_count} fixture rows**. ${r.supervision.post_removal_note}`);
      }
    } else {
      L.push(`- Contamination guard: ${r.supervision.exemplar_count} exemplars, ${r.supervision.rule_domain_count} declared rule domains, matched on ${r.supervision.matching_unit}; **${violations} violations**`);
    }
    if (r.engine_details && r.engine_details.fixture_overlap_entries_removed !== undefined) {
      L.push(`  - UT1 table: ${r.engine_details.entries_before_overlap_removal} hosts compiled, ${r.engine_details.fixture_overlap_entries_removed} removed for fixture eTLD+1 overlap, ${r.engine_details.entries_after_overlap_removal} used.`);
    }
    L.push(`- Abstentions: ${JSON.stringify(r.abstain_breakdown)}`);
    L.push(`- Leakage diagnostic: top-1 accuracy on covered rows ${fmt(r.leakage_diagnostic.top1_accuracy_on_covered)}, ${r.leakage_diagnostic.classes_at_precision_1} classes at precision 1.0`);
    if (r.charitable_ambiguous_scoring) {
      L.push(`- Charitable re-scoring of the ${c.ambiguous_rows} labeller-flagged ambiguous rows: macro-F1 (evaluable) ${fmt(r.charitable_ambiguous_scoring.macro_f1_evaluable)} vs strict ${fmt(r.macro_f1_evaluable.value)}. Only labels inside the labeller's own defensible set are credited, so a zero-gold label can never gain a gold positive.`);
    }
    const s = r.sensitivity;
    L.push(`- Sensitivity: leave-one-domain-out macro-F1 range ${fmt(s.leave_one_etld1_out.min)}–${fmt(s.leave_one_etld1_out.max)}; leave-one-persona-out ${fmt(s.leave_one_persona_out.min)}–${fmt(s.leave_one_persona_out.max)}`);
    if (r.coverage_accuracy_sweep && Array.isArray(r.coverage_accuracy_sweep)) {
      L.push('');
      L.push(`  Coverage vs accuracy (recomputed from ungated scores, axis \`${r.coverage_accuracy_sweep[0]?.axis}\`):`);
      L.push('');
      L.push('  | threshold | coverage | accuracy (lenient) | accuracy (strict) | covered rows |');
      L.push('  |---|---|---|---|---|');
      for (const p of r.coverage_accuracy_sweep) {
        L.push(`  | ${p.threshold} | ${pct(p.coverage)} | ${fmt(p.accuracy_lenient)} | ${fmt(p.accuracy_strict)} | ${p.covered_rows} |`);
      }
    } else if (r.coverage_accuracy_sweep) {
      L.push(`- Coverage/accuracy sweep: not applicable — ${r.coverage_accuracy_sweep.reason}`);
    }
    L.push('');
  }

  if (parity) {
    L.push('## Phase A artifact parity across architectures');
    L.push('');
    L.push(`Compared the \`${parity.arch_a}\` and \`${parity.arch_b}\` Phase A download manifests. Model binaries and the compiled UT1 table are never committed, so these digests are the durable evidence.`);
    L.push('');
    L.push(`- Model artifact files compared: **${parity.summary.files_identical}/${parity.summary.files_compared} byte-identical** by SHA-256.`);
    if (parity.ut1.compared) {
      L.push(`- Compiled UT1 host→label table: digest ${parity.ut1.compiled_sha256_match ? `**identical** (\`${parity.ut1.compiled_sha256.slice(0, 16)}…\`)` : '**DIFFERS**'}, ${parity.ut1.total_hosts} hosts, ${parity.ut1.category_digest_mismatches.length} category digest mismatches.`);
    } else {
      L.push(`- Compiled UT1 table: not compared — ${parity.ut1.reason}.`);
    }
    L.push(`- ${parity.note}`);
    L.push('');
  }

  if (cross) {
    L.push('## Cross-architecture comparison');
    L.push('');
    L.push(`Compared \`${cross.arch_a}\` against \`${cross.arch_b}\`${cross.emulation_note ? ` (${cross.emulation_note})` : ''}.`);
    if (cross.completeness_note) L.push(`\n**${cross.complete ? 'Complete' : 'Incomplete'}:** ${cross.completeness_note}.`);
    L.push('');
    L.push('| Candidate | Decisions identical | Raw scores bitwise identical | Differing label SETS | Order-only differences | Raw top-1 changes | Set differences with unchanged raw top-1 |');
    L.push('|---|---|---|---|---|---|---|');
    for (const [id, v] of Object.entries(cross.per_candidate)) {
      L.push(v.measured
        ? `| \`${id}\` | ${v.decision_hash_match ? 'yes' : 'no'} | ${v.raw_score_hash_match ? 'yes' : 'no'} | ${v.differing_label_sets ?? 'not measured'} | ${v.differing_label_order_only ?? 'not measured'} | ${v.differing_raw_top1 ?? 'not measured'} | ${v.set_differences_without_raw_top1_change ?? 'not measured'} |`
        : `| \`${id}\` | not measured | not measured | not measured | not measured | not measured | not measured |`);
    }
    L.push('');
    L.push('> **Read the label-SET column, not the sequence.** `predicted` is emitted in descending-score order, so a pure rank permutation of an identical label set is not a decision difference. Set and order are counted separately here for that reason.');
    L.push('>');
    L.push('> The last column isolates rows where the label set moved while the model\'s own top choice did NOT: those are the fixed, unswept multi-label emission band admitting or dropping a borderline label, so they measure threshold sensitivity as much as architecture.');
    if (cross.note) L.push(`>\n> ${cross.note}`);
    L.push('');
  } else {
    L.push('## Cross-architecture comparison');
    L.push('');
    L.push('**Not measured in this run.** No `results/cross-arch-comparison.json` exists. Cross-architecture determinism is therefore UNKNOWN for every candidate here and must not be inferred from the same-architecture result.');
    L.push('');
  }

  L.push('## What this run does NOT tell you');
  L.push('');
  L.push(`- **Adult-content recall.** ${lim.adult_note}`);
  L.push(`- **Recall for ${lim.zero_gold_labels.map((l) => `\`${l}\``).join(', ')}** — no gold rows exist.`);
  L.push('- **Whether close candidates are genuinely separated.** Read the bootstrap CI column: intervals that overlap are not a ranking. Three macro policies give three different orderings.');
  {
    // Configuration-aware: the previous blanket claim was false for the
    // as-published UT1 configuration sitting in the same table.
    const strict = rows.find((r) => r.engine_details && r.engine_details.overlap_removal_applied === true);
    const full = rows.find((r) => r.engine_details && r.engine_details.overlap_removal_applied === false);
    const parts = ['- **Production coverage for the list tier.**'];
    if (strict) parts.push(`\`${strict.id}\` removes every fixture registrable domain before measurement, so its ${pct(strict.coverage)} is a lower bound by construction.`);
    if (full) parts.push(`\`${full.id}\` measures the published table as-is at ${pct(full.coverage)} on ${full.supervision.post_removal_fixture_hits} matching rows.`);
    parts.push('**Neither bounds production coverage:** the strict figure is zero by construction, and nothing measured here bounds the full list from above.');
    L.push(parts.join(' '));
  }
  L.push('- **Non-English behaviour**, and **token-level (visit-weighted) prevalence** — the fixture is type-deduplicated.');
  L.push('- **A calibrated operating point.** Every candidate is reported at a hand-chosen threshold and a hand-chosen, unswept multi-label emission band, in units that differ by score axis. These are not calibrated operating points and must not be read as tuned ones.');
  if (cross && !cross.complete) {
    L.push(`- **Cross-architecture behaviour of ${cross.unmeasured_candidates.map((id) => `\`${id}\``).join(', ')}** — no complete \`${cross.arch_b}\` prediction artifact exists for these configurations.`);
  }
  L.push('');
  L.push('---');
  L.push('');
  L.push('UT1 blacklist data is © Université Toulouse 1 Capitole, licensed CC BY-SA 4.0 (https://dsi.ut-capitole.fr/blacklists/). The compiled host→label table is a derivative work under the same licence.');
  L.push('');

  const out = path.join(RESULTS_DIR, 'leaderboard.md');
  fs.writeFileSync(out, L.join('\n'));
  console.log(`Wrote ${out}`);
}

main();
